name: StaffMode
version: 1.0
main: dev.darkhorizon.es.sm.Main
depend: [Essentials]
commands:
  staff:
    description: Staff Mode command
    usage: /<command>
    aliases: [sm, staffm, staffmode, smode]
  examine:
    usage: <command>
    aliases: [examinar]
  freeze:
    usage: <command>
    aliases: [ss, congelar]
  stafflist:
    usage: <command>
    aliases: [slist, staffl]
  playertp:
    usage: <command>
  spec:
    usage: <command>
    aliases: [espectar, spectate]
  punish:
    usage: <command>
    aliases: [bangui, guiban, sancionar]
  setpunish:
    usage: <command>
    aliases: [setpunishloc]
